In [31]:
from bs4 import BeautifulSoup
import requests

In [32]:
url = "https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue"

headers = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
}

page = requests.get(url, headers=headers)
soup = BeautifulSoup(page.text, "html")

In [43]:
table = soup.find('table', class_ = "wikitable sortable")

In [44]:
world_titles = table.find_all('th')

In [45]:
world_table_titles = [title.text for title in world_titles]
print(world_table_titles)

['Rank', 'Name', 'Industry', 'Revenue (USD millions)', 'Revenue growth', 'Employees', 'Headquarters']

In [47]:
import pandas as pd

In [48]:
df = pd.DataFrame(columns = world_table_titles)
df

Empty DataFrame
Columns: [Rank, Name, Industry, Revenue (USD millions), Revenue growth, Employees, Headquarters]
Index: []

In [49]:
column_data = table.find_all('tr')

In [60]:
for row in column_data[1:]:
    row_data = (row.find_all('td'))
    individual_row_data = [data.text for data in row_data]

    length = len(df)
    df.loc[length] = individual_row_data

In [61]:
df

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
0,1,Walmart,Retail,"680,985",5.1%,"2,100,000","Bentonville, Arkansas"
1,2,Amazon,Retail and cloud computing,"637,959",11.0%,"1,556,000","Seattle, Washington"
2,3,UnitedHealth Group,Healthcare,"400,278",7.7%,"400,000","Minnetonka, Minnesota"
3,4,Apple,Technology,"391,035",2.0%,"164,000","Cupertino, California"
4,5,CVS Health,Healthcare,"372,809",4.2%,"259,500","Woonsocket, Rhode Island"
...,...,...,...,...,...,...,...
195,96,General Dynamics,Aerospace and defense,"47,716",12.9%,"117,000","Reston, Virginia"
196,97,Coca-Cola,Beverage,"47,061",2.9%,"69,700","Atlanta, Georgia"
197,98,TIAA,Financials,"46,946",2.6%,"15,623","New York City, New York"
198,99,Travelers,Insurance,"46,423",12.2%,"34,000","New York City, New York"
199,100,Eli Lilly,Pharmaceutical,"45,043",32.0%,"47,000","Indianapolis, Indiana"

In [59]:
df.to_csv(r'/Users/Robert/Desktop/python tutorial/Companies.csv', index = False)